export type Prompt = {
  id: number
  prompt: string
  category: string
}

export const PROMPTS: Prompt[] = [
  { id: 2, prompt: 'Player with the longest beard', category: 'appearance' },
  { id: 3, prompt: 'Shortest player at the table', category: 'appearance' },
  { id: 8, prompt: 'Player wearing the most colors', category: 'appearance' },
  { id: 12, prompt: 'Player with the longest hair', category: 'appearance' },
  { id: 21, prompt: 'Last player who had a haircut', category: 'appearance' },
  { id: 58, prompt: 'Player whose shoe size is largest', category: 'appearance' },
  { id: 101, prompt: 'Last player who talked to themselves and got caught', category: 'chaos' },
  { id: 102, prompt: 'Player who most recently Googled something embarrassing', category: 'chaos' },
  { id: 103, prompt: 'Last player who tripped over nothing', category: 'chaos' },
  { id: 104, prompt: 'Player who most recently sent a message to the wrong person', category: 'chaos' },
  { id: 105, prompt: 'Last player who laughed at their own joke before finishing it', category: 'chaos' },
  { id: 106, prompt: 'Player who most recently forgot why they walked into a room', category: 'chaos' },
  { id: 107, prompt: 'Last player who waved back at someone who wasn\'t waving at them', category: 'chaos' },
  { id: 108, prompt: 'Player who most recently said \'you too\' when told to enjoy their meal', category: 'chaos' },
  { id: 109, prompt: 'Last player who called a teacher \'mom\' or \'dad\'', category: 'chaos' },
  { id: 110, prompt: 'Player with the most expired items in their bag right now', category: 'chaos' },
  { id: 111, prompt: 'Last player who confidently walked in the wrong direction and kept going anyway', category: 'chaos' },
  { id: 112, prompt: 'Player who most recently dropped their phone on their face in bed', category: 'chaos' },
  { id: 113, prompt: 'Last player who replied \'I\'m on my way\' while still at home', category: 'chaos' },
  { id: 114, prompt: 'Player who pushed a \'pull\' door the hardest before reading the sign', category: 'chaos' },
  { id: 115, prompt: 'Last player who auto-corrected into something mortifying', category: 'chaos' },
  { id: 116, prompt: 'Player who most recently fell asleep somewhere weird', category: 'chaos' },
  { id: 117, prompt: 'Last player who tried to unlock someone else\'s car by mistake', category: 'chaos' },
  { id: 118, prompt: 'Player who most recently talked during a movie they\'d already seen', category: 'chaos' },
  { id: 119, prompt: 'Last player who Googled a word they definitely should know', category: 'chaos' },
  { id: 120, prompt: 'Player who most recently walked into a glass door or window', category: 'chaos' },
  { id: 121, prompt: 'Last player who accidentally liked an old photo while stalking someone\'s profile', category: 'chaos' },
  { id: 122, prompt: 'Player who most recently set an alarm and slept through it anyway', category: 'chaos' },
  { id: 123, prompt: 'Last player who forgot a name mid-introduction', category: 'chaos' },
  { id: 124, prompt: 'Player who most recently said goodbye and then walked the same direction as the other person', category: 'chaos' },
  { id: 125, prompt: 'Last player who tried to pay with an empty card', category: 'chaos' },
  { id: 126, prompt: 'Player who most recently wore something inside out all day without noticing', category: 'chaos' },
  { id: 127, prompt: 'Last player who yelled at a buffering screen', category: 'chaos' },
  { id: 128, prompt: 'Player who most recently ordered the wrong thing and ate it anyway out of shame', category: 'chaos' },
  { id: 129, prompt: 'Last player who gave extremely confident directions that were completely wrong', category: 'chaos' },
  { id: 130, prompt: 'Player who most recently searched for their phone while it was in their hand', category: 'chaos' },
  { id: 131, prompt: 'Last player who started a story and completely forgot the point', category: 'chaos' },
  { id: 132, prompt: 'Player who most recently rehearsed an argument in the shower', category: 'chaos' },
  { id: 133, prompt: 'Last player who apologized to furniture they bumped into', category: 'chaos' },
  { id: 135, prompt: 'Last player who put the milk in the cabinet and the cereal in the fridge', category: 'chaos' },
  { id: 137, prompt: 'Last player who confidently answered a question and was spectacularly wrong', category: 'chaos' },
  { id: 139, prompt: 'Last player who read a whole page and absorbed absolutely nothing', category: 'chaos' },
  { id: 140, prompt: 'Player who most recently had a full conversation and couldn\'t remember a word of it', category: 'chaos' },
  { id: 141, prompt: 'Last player who bought something \'on sale\' they didn\'t need and called it saving money', category: 'chaos' },
  { id: 142, prompt: 'Player who most recently looked for something while someone else found it immediately', category: 'chaos' },
  { id: 165, prompt: 'Last player who checked the time and immediately forgot what it was', category: 'chaos' },
  { id: 166, prompt: 'Player who most recently had a full debate with a self-checkout machine', category: 'chaos' },
  { id: 169, prompt: 'Last player who said \'I\'ll remember that\' and did not remember that', category: 'chaos' },
  { id: 170, prompt: 'Player who most recently fell asleep while replying to a message', category: 'chaos' },
  { id: 171, prompt: 'Last player who used \'I was just about to do that\' as a defence', category: 'chaos' },
  { id: 172, prompt: 'Player who most recently opened an app forgot why closed it and reopened it', category: 'chaos' },
  { id: 174, prompt: 'Player who most recently took a nap that became a full sleep', category: 'chaos' },
  { id: 175, prompt: 'Last player who tried to parallel park and gave up', category: 'chaos' },
  { id: 176, prompt: 'Player who most recently called something \'basically the same thing\' when it clearly wasn\'t', category: 'chaos' },
  { id: 178, prompt: 'Player who most recently said \'I\'m almost ready\' and wasn\'t even close', category: 'chaos' },
  { id: 179, prompt: 'Last player who made a bold prediction in front of witnesses and was catastrophically wrong', category: 'chaos' },
  { id: 181, prompt: 'Last player who watched a tutorial and still couldn\'t figure it out', category: 'chaos' },
  { id: 182, prompt: 'Player who most recently said \'I\'ll start fresh on Monday\' on a Thursday', category: 'chaos' },
  { id: 187, prompt: 'Last player who convinced themselves they\'d remember something without writing it down — and didn\'t', category: 'chaos' },
  { id: 189, prompt: 'Last player who dramatically said \'I\'m going to bed\' and was back 10 minutes later', category: 'chaos' },
  { id: 190, prompt: 'Player who most recently used \'I meant to do that\' after clearly not meaning to', category: 'chaos' },
  { id: 192, prompt: 'Player who most recently discovered food in their pocket they had forgotten about', category: 'chaos' },
  { id: 193, prompt: 'Last player who looked at the time on their phone and immediately picked it up again to check', category: 'chaos' },
  { id: 196, prompt: 'Player who most recently narrated their own actions out loud while alone', category: 'chaos' },
  { id: 199, prompt: 'Last player who said \'let me check real quick\' and disappeared for 20 minutes', category: 'chaos' },
  { id: 13, prompt: 'Last person who visited a museum', category: 'culture' },
  { id: 15, prompt: 'Last player who read a book', category: 'culture' },
  { id: 47, prompt: 'Last player who learned something new', category: 'culture' },
  { id: 51, prompt: 'Last player who painted or drew something', category: 'culture' },
  { id: 88, prompt: 'Player who most recently visited a library', category: 'culture' },
  { id: 89, prompt: 'Last player who bought a book', category: 'culture' },
  { id: 10, prompt: 'Player who woke up earliest today', category: 'daily life' },
  { id: 14, prompt: 'Player who most recently bought something online', category: 'daily life' },
  { id: 18, prompt: 'Player with the most steps today', category: 'daily life' },
  { id: 19, prompt: 'Last player who took a photo', category: 'daily life' },
  { id: 22, prompt: 'Player who most recently stayed up past midnight', category: 'daily life' },
  { id: 34, prompt: 'Player with the oldest item in their pocket or bag', category: 'daily life' },
  { id: 38, prompt: 'Player with the most unread messages', category: 'daily life' },
  { id: 43, prompt: 'Last player who fixed something broken', category: 'daily life' },
  { id: 44, prompt: 'Player with the most apps on their phone', category: 'daily life' },
  { id: 46, prompt: 'Player who woke up latest today', category: 'daily life' },
  { id: 57, prompt: 'Last player who climbed stairs instead of taking the elevator', category: 'daily life' },
  { id: 61, prompt: 'Last player who overslept', category: 'daily life' },
  { id: 62, prompt: 'Player with the most keys on their keychain', category: 'daily life' },
  { id: 66, prompt: 'Player who has the most photos on their phone', category: 'daily life' },
  { id: 70, prompt: 'Player with the earliest alarm set for tomorrow', category: 'daily life' },
  { id: 76, prompt: 'Player with the most tabs open in their browser', category: 'daily life' },
  { id: 82, prompt: 'Player who most recently had a nightmare', category: 'daily life' },
  { id: 86, prompt: 'Player with the fewest social media accounts', category: 'daily life' },
  { id: 90, prompt: 'Player who most recently got a parking ticket', category: 'daily life' },
  { id: 93, prompt: 'Last player who made a phone call (not a message)', category: 'daily life' },
  { id: 95, prompt: 'Last player who sat on the floor', category: 'daily life' },
  { id: 97, prompt: 'Last player who went to bed after 2am', category: 'daily life' },
  { id: 7, prompt: 'Last player who watched a movie', category: 'entertainment' },
  { id: 25, prompt: 'Last player who cried at a movie', category: 'entertainment' },
  { id: 84, prompt: 'Player who watched the most episodes of a show this week', category: 'entertainment' },
  { id: 134, prompt: 'Player who most recently binge-watched something they weren\'t even enjoying', category: 'entertainment' },
  { id: 138, prompt: 'Player who most recently fell asleep during a movie they chose', category: 'entertainment' },
  { id: 143, prompt: 'Last player who asked \'what are we watching?\' and then stared at their phone the whole time', category: 'entertainment' },
  { id: 167, prompt: 'Last player who gave an overly confident opinion on a film they watched on 1.5x speed', category: 'entertainment' },
  { id: 198, prompt: 'Player who most recently spent longer choosing what to watch than actually watching anything', category: 'entertainment' },
  { id: 30, prompt: 'Player with the most siblings', category: 'family' },
  { id: 54, prompt: 'Player with the most pets', category: 'family' },
  { id: 68, prompt: 'Player who most recently visited their grandparents', category: 'family' },
  { id: 5, prompt: 'Last player who cooked a meal', category: 'food' },
  { id: 11, prompt: 'Last player who ate pizza', category: 'food' },
  { id: 23, prompt: 'Last player who ate breakfast', category: 'food' },
  { id: 29, prompt: 'Last player who drank coffee', category: 'food' },
  { id: 31, prompt: 'Last player who tried a new restaurant', category: 'food' },
  { id: 39, prompt: 'Last player who baked something', category: 'food' },
  { id: 53, prompt: 'Last player who ordered food delivery', category: 'food' },
  { id: 73, prompt: 'Last player who burned food while cooking', category: 'food' },
  { id: 75, prompt: 'Last player who went to a farmer\'s market', category: 'food' },
  { id: 91, prompt: 'Last player who tried a food they had never eaten before', category: 'food' },
  { id: 136, prompt: 'Player who most recently stress-ate something from the back of the fridge', category: 'food' },
  { id: 156, prompt: 'Player who most recently ate something off the floor after the 3-second rule expired', category: 'food' },
  { id: 157, prompt: 'Last player who made a recipe \'their own\' by ignoring all the instructions', category: 'food' },
  { id: 158, prompt: 'Player who most recently called cereal a legitimate dinner', category: 'food' },
  { id: 159, prompt: 'Last player who finished someone else\'s leftovers and pretended not to know what happened', category: 'food' },
  { id: 160, prompt: 'Player who most recently ate snacks in bed and denied it', category: 'food' },
  { id: 161, prompt: 'Last player who confidently mispronounced a menu item at a restaurant', category: 'food' },
  { id: 162, prompt: 'Player who most recently burnt toast and ate it anyway', category: 'food' },
  { id: 163, prompt: 'Last player who said \'I\'m not even hungry\' and then ate the most', category: 'food' },
  { id: 164, prompt: 'Player who most recently looked in the fridge found nothing and checked again 3 minutes later', category: 'food' },
  { id: 9, prompt: 'Last player who lost a game', category: 'gaming' },
  { id: 28, prompt: 'Player who owns the most board games', category: 'gaming' },
  { id: 48, prompt: 'Player who has played this game the most times', category: 'gaming' },
  { id: 55, prompt: 'Last player who played a video game', category: 'gaming' },
  { id: 71, prompt: 'Last player who played a card game', category: 'gaming' },
  { id: 92, prompt: 'Player with the most board game losses this month', category: 'gaming' },
  { id: 144, prompt: 'Player who most recently rage-quit a game and immediately asked for a rematch', category: 'gaming' },
  { id: 145, prompt: 'Last player who said \'one more game\' and meant it the least', category: 'gaming' },
  { id: 146, prompt: 'Player who most recently blamed their bad play on game balance', category: 'gaming' },
  { id: 147, prompt: 'Last player who offered to teach the rules and then got them wrong', category: 'gaming' },
  { id: 148, prompt: 'Player who has the most house rules memorized that nobody else agreed to', category: 'gaming' },
  { id: 149, prompt: 'Last player who went all-in on a strategy and never recovered', category: 'gaming' },
  { id: 150, prompt: 'Player who most recently asked \'wait whose turn is it?\' when it was obviously theirs', category: 'gaming' },
  { id: 151, prompt: 'Last player who pretended to understand the rules and hoped for the best', category: 'gaming' },
  { id: 152, prompt: 'Player who most recently made a confident move and immediately regretted it', category: 'gaming' },
  { id: 153, prompt: 'Last player who kept score wrong and blamed the pen', category: 'gaming' },
  { id: 154, prompt: 'Player who most recently spent 10 minutes on their turn and still made the worst possible move', category: 'gaming' },
  { id: 155, prompt: 'Last player who pulled the \'I was going easy on you\' card after losing', category: 'gaming' },
  { id: 50, prompt: 'Player with the most plants at home', category: 'home' },
  { id: 79, prompt: 'Last player who changed a light bulb', category: 'home' },
  { id: 80, prompt: 'Player with the most items in their fridge', category: 'home' },
  { id: 87, prompt: 'Last player who tried to fix something with tape', category: 'home' },
  { id: 98, prompt: 'Player with the most stickers on their laptop or notebook', category: 'home' },
  { id: 168, prompt: 'Player who most recently panic-cleaned before guests arrived and hid things in a closet', category: 'home' },
  { id: 177, prompt: 'Last player who aggressively reorganized something that was already fine', category: 'home' },
  { id: 180, prompt: 'Player who most recently bought something \'for the house\' that was clearly just for them', category: 'home' },
  { id: 200, prompt: 'Player who most recently had strong feelings about the correct way to load a dishwasher', category: 'home' },
  { id: 4, prompt: 'Most recent birthday', category: 'life events' },
  { id: 32, prompt: 'Player who most recently changed jobs', category: 'life events' },
  { id: 36, prompt: 'Player who most recently moved home', category: 'life events' },
  { id: 40, prompt: 'Player whose birthday is coming up soonest', category: 'life events' },
  { id: 72, prompt: 'Player who most recently went to a wedding', category: 'life events' },
  { id: 17, prompt: 'Last player who sang out loud', category: 'music' },
  { id: 41, prompt: 'Last player who attended a concert', category: 'music' },
  { id: 67, prompt: 'Last player who whistled', category: 'music' },
  { id: 16, prompt: 'Player whose name comes first alphabetically', category: 'names' },
  { id: 1, prompt: 'Last player who went hiking', category: 'outdoors' },
  { id: 26, prompt: 'Player who most recently rode a bike', category: 'outdoors' },
  { id: 33, prompt: 'Last player who went swimming', category: 'outdoors' },
  { id: 35, prompt: 'Last player who played a sport', category: 'outdoors' },
  { id: 52, prompt: 'Player who most recently got rained on', category: 'outdoors' },
  { id: 60, prompt: 'Player who most recently visited a beach', category: 'outdoors' },
  { id: 78, prompt: 'Player who most recently ran', category: 'outdoors' },
  { id: 27, prompt: 'Last player who made someone laugh', category: 'social' },
  { id: 37, prompt: 'Last player who got a gift', category: 'social' },
  { id: 45, prompt: 'Last player who went to a party', category: 'social' },
  { id: 49, prompt: 'Last player who made a mistake and admitted it', category: 'social' },
  { id: 56, prompt: 'Player who most recently cried from laughing', category: 'social' },
  { id: 59, prompt: 'Last player who sent a handwritten note', category: 'social' },
  { id: 63, prompt: 'Last player who hugged someone', category: 'social' },
  { id: 64, prompt: 'Player who most recently bought flowers', category: 'social' },
  { id: 69, prompt: 'Last player who donated something', category: 'social' },
  { id: 77, prompt: 'Last player who got a compliment', category: 'social' },
  { id: 83, prompt: 'Last player who argued about something and was wrong', category: 'social' },
  { id: 85, prompt: 'Last player who helped a stranger', category: 'social' },
  { id: 94, prompt: 'Player who most recently changed their mind about something', category: 'social' },
  { id: 99, prompt: 'Last player who got surprised', category: 'social' },
  { id: 100, prompt: 'Player who would win in a staring contest — everyone stares and last one to blink goes first', category: 'social' },
  { id: 183, prompt: 'Last player who replied to a group chat 10 hours late as if the conversation was still live', category: 'social' },
  { id: 184, prompt: 'Player who most recently tried to be subtle and completely failed', category: 'social' },
  { id: 185, prompt: 'Last player who gave unsolicited advice that backfired immediately', category: 'social' },
  { id: 186, prompt: 'Player who most recently forgot a name moments after being introduced', category: 'social' },
  { id: 188, prompt: 'Player who most recently pretended to be busy to avoid a phone call', category: 'social' },
  { id: 191, prompt: 'Last player who held a door open for someone who was way too far away', category: 'social' },
  { id: 194, prompt: 'Player who most recently let the \'typing...\' bubble appear and then said nothing', category: 'social' },
  { id: 197, prompt: 'Last player who tried to explain a meme and killed it', category: 'social' },
  { id: 6, prompt: 'Player who traveled farthest to get here', category: 'travel' },
  { id: 20, prompt: 'Player who most recently visited a foreign country', category: 'travel' },
  { id: 24, prompt: 'Player who traveled the longest distance this year', category: 'travel' },
  { id: 42, prompt: 'Player who most recently stayed in a hotel', category: 'travel' },
  { id: 65, prompt: 'Last player who got lost', category: 'travel' },
  { id: 74, prompt: 'Player who lives farthest from here', category: 'travel' },
  { id: 81, prompt: 'Last player who stayed somewhere with no Wi-Fi', category: 'travel' },
  { id: 96, prompt: 'Player who most recently took public transport', category: 'travel' },
  { id: 173, prompt: 'Last player who confidently said \'I know a shortcut\' and made things worse', category: 'travel' },
  { id: 195, prompt: 'Last player who planned an entire trip in their head and then didn\'t go', category: 'travel' },
  { id: 201, prompt: 'Last player who pet a cat', category: 'daily life' },
  { id: 202, prompt: 'Last player who played with a dog', category: 'daily life' },
]
